src/Entity/TodoList.php
<?php

namespace App\Entity;

use App\Repository\TodoListRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=TodoListRepository::class)
 */
class TodoList
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="todoLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $priority;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $done=false;

    /**
     * @ORM\OneToMany(targetEntity=ListElement::class, mappedBy="list",cascade={"persist"})
     */
    private $listElements;

    /**
     * @ORM\ManyToMany(targetEntity=Label::class, inversedBy="todoLists")
     */
    private $labels;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hashId;

    public function __construct(User $user)
    {
        $this->user = $user;
        $this->listElements = new ArrayCollection();
        $this->labels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDone(): ?bool
    {
        return $this->done;
    }

    public function setDone(bool $done): self
    {
        $this->done = $done;

        return $this;
    }

    /**
     * @return Collection|ListElement[]
     */
    public function getListElements(): Collection
    {
        return $this->listElements;
    }

    public function addListElement(ListElement $listElement): self
    {
        if (!$this->listElements->contains($listElement)) {
            $this->listElements[] = $listElement;
            $listElement->setList($this);
        }

        return $this;
    }

    public function removeListElement(ListElement $listElement): self
    {
        if ($this->listElements->removeElement($listElement)) {
            // set the owning side to null (unless already changed)
            if ($listElement->getList() === $this) {
                $listElement->setList(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Label[]
     */
    public function getLabels(): Collection
    {
        return $this->labels;
    }

    public function addLabel(Label $label): self
    {
        if (!$this->labels->contains($label)) {
            $this->labels[] = $label;
        }

        return $this;
    }

    public function removeLabel(Label $label): self
    {
        $this->labels->removeElement($label);

        return $this;
    }

    public function getHashId(): ?string
    {
        return $this->hashId;
    }

    public function setHashId(string $hashId): self
    {
        $this->hashId = $hashId;

        return $this;
    }

    public function getElementsDoneStatus(): bool
    {
        $status =true;
        foreach($this->getListElements() as $element)
        {
            if(!$element->getDone())
            {
                $status = false;
                break;
            }
        }
        return $status;
    }

}

src/Controller/ListController.php
<?php

namespace App\Controller;

use App\Entity\ListElement;
use App\Entity\TodoList;
use App\Entity\User;
use App\Form\ListElementsType;
use App\Form\TodoListType;
use Doctrine\Common\Collections\ArrayCollection;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/list")
 */
class ListController extends AbstractController
{
    /**
     * @var TranslatorInterface
     */
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    /**
     * @Route("/{status}", name="list_my", defaults={"status":"active"}, requirements={"status":"active|done|all"})
     * @param Request $request
     * @param string $status
     * @return Response
     */
    public function index(Request $request,string $status): Response
    {
        $this->denyAccessUnlessGranted("ROLE_USER");
        $em=$this->getDoctrine()->getManager();
        $lists=$em->getRepository(TodoList::class)->getMyList($this->getUser(),$status);

        return $this->render('list/index.html.twig', [
            'lists' => $lists,
        ]);
    }

    /**
     * @Route("/new", name="app_new_list", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function newList(Request $request)
    {
        /** @var User $user */
        $user=$this->getUser();
        $list=new TodoList($user);
        $form=$this->createForm(TodoListType::class,$list);
        $form->handleRequest($request);
        if($form->isSubmitted()&&$form->isValid())
        {
            $list->setHashId(uniqid());
            $em=$this->getDoctrine()->getManager();
            $em->persist($list);
            $em->flush();
            $this->addFlash('success',$this->translator->trans('Dodano nową liste'));
            return $this->redirectToRoute('list_show',['id'=>$list->getId()]);
        }

        return $this->render('list/new.html.twig', [
           'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="list_show", methods={"GET"})
     * @param TodoList $list
     * @return Response
     */
    public function showList(TodoList $list): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        $elements=$em->getRepository(ListElement::class)->getListElementsSorted($list);
        return $this->render('list/show.html.twig', [
           'list'=>$list,
            'elements'=>$elements
        ]);
    }

    /**
     * @Route("/edit/{id}", name="list_edit", methods={"GET","POST"})
     * @param Request $request
     * @param TodoList $list
     * @return Response
     */
    public function editList(Request $request,TodoList $list): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $form=$this->createForm(TodoListType::class,$list);
        $form->handleRequest($request);
        if($form->isSubmitted()&&$form->isValid())
        {
            $em=$this->getDoctrine()->getManager();
            $em->persist($list);
            $em->flush();
            $this->addFlash('success',$this->translator->trans('Edycja listy zakończona powodzeniem'));
            return $this->redirectToRoute('list_show',['id'=>$list->getId()]);
        }

        return $this->render('list/edit.html.twig', [
            'form'=>$form->createView(),
            'list'=>$list
        ]);
    }

    /**
     * @Route("/delete/{id}",name="list_delete", methods={"DELETE"})
     * @param Request $request
     * @param TodoList $list
     * @return Response
     */
    public function deleteList(Request $request,TodoList $list): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }

        if ($this->isCsrfTokenValid('delete'.$list->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($list);
            foreach($list->getListElements() as $element)
            {
                $entityManager->remove($element);
            }
            $entityManager->flush();
        }

        return $this->redirectToRoute('list_my');
    }

    /**
     * @Route("/list/{id}/done", name="list_make_done",methods={"PATCH"})
     * @param Request $request
     * @param TodoList $list
     * @return Response
     */
    public function doneList(Request $request,TodoList $list): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        if($list->getElementsDoneStatus())
        {
            $list->setDone(!$list->getDone());
            $em->persist($list);
            $em->flush();
        }else{
            $this->addFlash('warning',$this->translator->trans('Nie można zakończyć listy, ukończ wszystkie elementy listy najpierw'));
        }
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/{id}/edit_elements", name="list_edit_elements", methods={"GET", "POST"})
     * @param Request $request
     * @param TodoList $list
     * @return RedirectResponse|Response
     */
    public function editListElements(Request $request, TodoList $list)
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        $originalElements=new ArrayCollection();
        $elements=$em->getRepository(ListElement::class)->getListElementsSorted($list);
        foreach ($elements as $element)
        {
            $originalElements->add($element);
        }
        $sort=sizeof($list->getListElements());
        for($i=0;$i<10;$i++)
        {
            $element=new ListElement();
            $sort++;
            $element->setSort($sort);
            $list->addListElement($element);
        }
        $form = $this->createForm(ListElementsType::class,$list);
        $form->handleRequest($request);
        if($form->isSubmitted()&&$form->isValid())
        {

            foreach($list->getListElements() as $element)
            {
                if(is_null($element->getContent()))
                {
                    $list->removeListElement($element);
                    if(false === $list->getListElements()->contains($element))
                    {
                        $em->remove($element);
                    }
                }
            }

            $em->persist($list);
            $em->flush();
            $this->addFlash('success',$this->translator->trans('Edycja zakończona sukcesem'));
            return $this->redirectToRoute('list_show',['id'=>$list->getId()]);
        }

        return $this->render('list/_elements_form.html.twig', [
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/list/{parent_id}/element/{child_id}/done", name="list_element_make_done",methods={"PATCH"})
     * @ParamConverter("list", options={"mapping": {"parent_id": "id"}})
     * @ParamConverter("element", options={"mapping": {"child_id": "id"}})
     * @param Request $request
     * @param TodoList $list
     * @param ListElement $element
     * @return Response
     */
    public function doneElement(Request $request,TodoList $list,ListElement $element): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        $element->setDone(!$element->getDone());
        $em->persist($element);
        $em->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/list/{id}/done_all", name="list_element_make_done_all",methods={"PATCH"})
     * @param Request $request
     * @param TodoList $list
     * @return Response
     */
    public function doneAllElements(Request $request,TodoList $list): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        foreach ($list->getListElements() as $element)
        {
            $element->setDone(true);
            $em->persist($element);
        }
        $em->flush();
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/list/{parent_id}/element/{sort}/delete", name="list_element_delete",methods={"DELETE"})
     * @ParamConverter("list", options={"mapping": {"parent_id": "id"}})
     * @param Request $request
     * @param TodoList $list
     * @param ListElement $element
     * @return Response
     */
    public function deleteElement(Request $request,TodoList $list,ListElement $element): Response
    {
        if($list->getUser()!==$this->getUser())
        {
            return $this->redirectToRoute('list_my');
        }
        $em=$this->getDoctrine()->getManager();
        $otherElements=$em->getRepository(ListElement::class)->getElementWithHiggerSort($element->getList(),$element->getSort());
        foreach ($otherElements as $otherElement)
        {
            $otherElement->setSort($otherElement->getSort()-1);
            $em->persist($otherElement);
        }
        $em->remove($element);
        $em->flush();

templates/list/_delete_form.html.twig
<form method="post" action="{{ path('list_delete', {'id': list.id}) }}" onsubmit="return confirm('Na pewno chcesz usunąć tą listę?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ list.id) }}">
    <button class="btn btn-dark btn-sm">Usuń listę</button>
</form>

templates/list/_done_form.html.twig
<form method="post" action="{{ path('list_make_done', {'id': list.id}) }}" onsubmit="return confirm('Na pewno?');">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token('patch' ~ list.id) }}">
    <button class="btn btn-success btn-sm">
        {% if list.done %}
            Oznacz jako nie wykonane
        {% else %}
            Oznacz jako wykonane
        {% endif %}
    </button>
</form>

templates/list/_element_delete_form.html.twig
<form method="post" action="{{ path('list_element_delete', {'sort': element.sort,'parent_id': element.list.id}) }}" onsubmit="return confirm('Na pewno chcesz usunąć ten element?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ element.id) }}">
    <button class="btn btn-dark btn-sm">Usuń</button>
</form>

templates/list/_element_done_all_form.html.twig
<form method="post" action="{{ path('list_element_make_done_all', {'id': list.id}) }}" onsubmit="return confirm('Na pewno?');">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token('patch' ~ list.id) }}">
    <button class="btn btn-success btn-sm mb-2">
            Oznacz wszystkie jako nie wykonane
    </button>
</form>

templates/list/_element_done_form.html.twig
<form method="post" action="{{ path('list_element_make_done', {'child_id': element.id,'parent_id': element.list.id}) }}" onsubmit="return confirm('Na pewno?');">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token('patch' ~ element.id) }}">
    <button class="btn btn-success btn-sm">
        {% if element.done %}
            Oznacz jako nie wykonane
        {% else %}
            Oznacz jako wykonane
        {% endif %}
    </button>
</form>

templates/list/_element_move_form.html.twig
<form method="post" action="{{ path('list_element_move', {'sort': element.sort,'parent_id': element.list.id, 'type': type}) }}">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="_token" value="{{ csrf_token('patch' ~ element.id) }}">
    <button class="btn btn-outline-primary btn-sm">
        {% if type == 'up'%}
            Przesuń wyżej
        {% else %}
            Przesuń niżej
        {% endif %}
    </button>
</form>

templates/list/_elements_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dodaj/edytuj elementy listy{% endblock %}

{% block body %}
{{ form_start(form) }}
    {% for key,element in form.list_elements %}
        <div class="row form-group">
            {% for child in element.children %}
                {% if(child.vars.label=='Element') %}
                <div class="col-12 col-sm-3 col-form-label">
                    {{ form_label(child,(key+1)~" "~child.vars.label) }}
                </div>
                <div class="col-12 col-sm-9">
                    {{ form_widget(child) }}
                </div>
                {% else %}
                    {{ form_widget(child) }}
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}

{{ form_end(form) }}
{% endblock %}

templates/list/_form.html.twig
{{ form_start(form) }}
    <div class="form-group row">
        <div class="col-12 col-sm-3 col-form-label">
            {{form_label(form.name)}}
        </div>
        <div class="col-12 col-sm-9 d-flex">
            {{ form_widget(form.name) }}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-12 col-sm-3 col-form-label">
            {{form_label(form.description)}}
        </div>
        <div class="col-12 col-sm-9 d-flex">
            {{ form_widget(form.description) }}
        </div>
    </div>
<div class="form-group row">
    <div class="col-12 col-sm-3 col-form-label">
        {{form_label(form.priority)}}
    </div>
    <div class="col-12 col-sm-9 d-flex">
        {{ form_widget(form.priority) }}
    </div>
</div>
<div class="form-group row">
    <div class="col-12 col-sm-3 col-form-label">
        {{form_label(form.labels)}}
    </div>
    <div class="col-12 col-sm-9 d-flex">
        {{ form_widget(form.labels) }}
    </div>
</div>

{{ form_end(form) }}

templates/list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edycja listy{% endblock %}

{% block body %}
    <h1>Edytuj listę</h1>

    {{ include('list/_form.html.twig') }}
    <div class="btn-group">
    <a class="btn btn-secondary" href="{{ path('list_my') }}">Powrót do listy</a>
    {{ include('list/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Moje zadania do zrobienia{% endtrans %}{% endblock %}

{% block body %}
    <h1>Moje zadania</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Data dodania</th>
            <th>Piorytet</th>
            <th>Status</th>
            <th>Akcje</th>
        </tr>
        </thead>
        <tbody>
        {% for list in lists %}
            <tr>
                <td><a href="{{ path('list_show',{id:list.id}) }}">{{ list.name }}</a></td>
                <td>{{ list.createdAt|date('d/m/Y H:i')}}</td>
                <td>{{ list.priority|list_priority }}</td>
                <td>
                    {% if list.elementsDoneStatus %}
                    {{ include('list/_done_form.html.twig') }}
                        {% else %}
                        Nie można zakończyć listy
                    {% endif %}
                </td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <a href="{{ path('list_edit',{id:list.id}) }}" class="btn btn-secondary">Edytuj</a>
                        {{ include('list/_delete_form.html.twig') }}
                    </div>
                </td>
            </tr>

        {% else %}
            <tr>
                <td colspan="4">Brak wyników</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_new_list') }}">Dodaj nowe zadanie</a>
{% endblock %}

templates/list/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nowe zadanie{% endblock %}

{% block body %}
    <h1>Dodaj nową liste</h1>

    {{ include('list/_form.html.twig') }}

    <a class="btn btn-secondary" href="{{ path('list_my') }}">Powrót do listy</a>
{% endblock %}

templates/list/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ list.name }}{% endblock %}

{% block body %}
    <h1>{{ list.name }}</h1>

    <p class="font-weight-bold">Opis:</p>
    <p>{{ list.description }}</p>
    <p>Priorytet: {{ list.priority|list_priority }}</p>
    {% if list.labels|length>0 %}
        <div class="w-100 mb-2">
            {% for label in list.labels %}
                <span class="badge badge-info">{{ label.name }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <p>
        {% if list.done %}
            Wykonane
        {% else %}
            {% if list.elementsDoneStatus %}
                {{ include('list/_done_form.html.twig') }}
            {% else %}
                Zakończ wszystkie elementy listy aby móc zakończyć listę
            {% endif %}
        {% endif %}
    </p>
    <p>
        Link do udostępnienia: <a href="{{ path('share_list',{hashId:list.hashId}) }}" target="_blank">{{ url('share_list',{hashId:list.hashId}) }}</a>
    </p>

    {% if elements|length>0 %}
    <ul class="list-group mb-2">
        {% for key,element in elements%}
        <li class="list-group-item d-flex">
            <p class="mb-0 mr-2">{{ element.content }}</p>
            <div class="btn-group btn-group-sm">
                {{ include('list/_element_done_form.html.twig') }}
                {% if key>0 %}
                    {{ include('list/_element_move_form.html.twig',{type:'up'}) }}
                {% endif %}
                {% if (key+1)<elements|length %}
                    {{ include('list/_element_move_form.html.twig',{type:'down'}) }}
                {% endif %}
                {{ include('list/_element_delete_form.html.twig') }}
            </div>

        </li>
        {% endfor%}
    </ul>
{% if list.elementsDoneStatus == false %}
    {{ include('list/_element_done_all_form.html.twig') }}
    {% endif %}
    {% endif %}

<div class="btn-group btn-group-sm">
    <a class="btn btn-primary" href="{{ path('list_my') }}">Powrót do listy</a>

    <a class="btn btn-secondary" href="{{ path('list_edit', {'id': list.id}) }}">Edycja</a>
    <a class="btn btn-outline-primary" href="{{ path('list_edit_elements', {'id': list.id}) }}">Dodaj/Edytuj elementy listy</a>
    {{ include('list/_delete_form.html.twig') }}
</div>

{% endblock %}